// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailHeading: "你嘅註冊驗證碼係",
		mailText: "歡迎嚟到 KIRAKIRA，用呢個驗證碼嚟註冊你嘅帳戶啦！\n驗證碼有效期 30 分鐘。請確保唔好將你嘅驗證碼洩露俾其他人。\n想停止接收通知，請聯絡 KIRAKIRA 支援團隊。",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA - 電郵變更驗證碼",
		mailHeading: "你嘅電郵變更驗證碼係",
		mailText: "驗證碼有效期 30 分鐘。請確保唔好將你嘅驗證碼洩露俾其他人。\n想停止接收通知，請聯絡 KIRAKIRA 支援團隊。",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA - 密碼變更驗證碼",
		mailHeading: "你嘅密碼變更驗證碼係",
		mailText: "驗證碼有效期 30 分鐘。請確保唔好將你嘅驗證碼洩露俾其他人。\n想停止接收通知，請聯絡 KIRAKIRA 支援團隊。",
	},
	SendLoginVerificationCode: {
		mailText: "驗證碼有效期 30 分鐘。請確保唔好將你嘅驗證碼洩露俾其他人。\n想停止接收通知，請聯絡 KIRAKIRA 支援團隊。",
	},
	SendDisableUserEmail2FAVerificationCode: {
		mailText: "驗證碼有效期 30 分鐘。請確保唔好將你嘅驗證碼洩露俾其他人。\n想停止接收通知，請聯絡 KIRAKIRA 支援團隊。",
	},
}
