// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "KIRAKIRA - 注冊驗證碼",
	},
	SendChangeEmailVerificationCode: {},
	SendChangePasswordVerificationCode: {},
	UserEmailAuthenticator: {},
	DeleteUserEmailAuthenticator: {},
}
