// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "KIRAKIRA-登録確認コード",
		mailHeading: "登録確認コードは",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA-メール確認コードの変更",
		mailHeading: "メールアドレスの確認コードは",
		mailText: "認証コードは30分間有効です。他人に確認コードを開示しないようにしてください。\n通知の受信を停止するには、KIRAサポートチームまでご連絡ください。",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA-パスワード認証コードの変更",
		mailHeading: "パスワードの確認コードは",
		mailText: "認証コードは30分間有効です。他人に確認コードを開示しないようにしてください。\n通知の受信を停止するには、KIRAサポートチームまでご連絡ください。",
	},
	UserEmailAuthenticator: {
		mailTitle: "KIRAKIRA-2FA認証のための認証コード",
		mailHeading: "認証システムを確認するための認証コードは",
	},
	DeleteUserEmailAuthenticator: {
		mailTitle: "KIRAKIRA-2FA削除のための認証コード",
		mailHeading: "認証システムを削除するための認証コードは",
	},
}
