name: Sync Crowdin

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史记录，以便删除远程分支

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Crowdin CLI
      run: npm install -g @crowdin/cli

    - name: Delete remote translations branch (if exists)
      run: |
        git fetch origin
        if git ls-remote --exit-code --heads origin translations; then
          git push origin --delete translations
        fi

    - name: Create new translations branch
      run: |
        git checkout develop
        git pull origin develop
        git checkout -b translations

    - name: Upload source files to Crowdin
      run: crowdin upload sources --token ${{ secrets.CROWDIN_PERSONAL_TOKEN }} --project-id ${{ secrets.CROWDIN_PROJECT_ID }} -c crowdin.yml
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Download translations from Crowdin
      run: crowdin download --token ${{ secrets.CROWDIN_PERSONAL_TOKEN }} --project-id ${{ secrets.CROWDIN_PROJECT_ID }} -c crowdin.yml
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Commit and push translations
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "🌐 更新翻译" || echo "No changes to commit"
        git push --set-upstream origin translations --force

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: translations
        base: develop
        title: "🌐 更新翻译"
        body: "由 GitHub Actions 自动生成的翻译更新 PR。"
        labels: "translation, automated"
        assignees: "github-actions[bot]"
